return {
    "stevearc/conform.nvim",
    event = "BufWritePre",
    cmd = { "ConformInfo" },
    opts = {
        formatters_by_ft = {
            lua = { "stylua" },
            python = { "ruff_format" },
            javascript = { "prettier" },
            javascriptreact = { "prettier" },
            typescript = { "prettier" },
            typescriptreact = { "prettier" },
            json = { "prettier" },
            jsonc = { "prettier" },
            yaml = { "prettier" },
            markdown = { "prettier" },
            css = { "prettier" },
            html = { "prettier" },
            c = { "clang-format" },
            cpp = { "clang-format" },
            go = { "goimports" },
            rust = { "rustfmt" },
            cs = { "csharpier" },
            java = { "google-java-format" },
            latex = { "latexindent" },
            typst = { "typstfmt" },
        },
        format_on_save = {
            lsp_fallback = true,
            timeout_ms = 1000,
        },
    },
}
